import Link from "next/link";

const currentIssue = { date: "September 14, 2026", title: "The first signal", description: "A concise field note on the ideas, tools, and shifts worth carrying forward." };

export default function Home() {
  return <main className="min-h-screen overflow-x-hidden bg-[#071716] text-[#f6f1e6]"><div className="pointer-events-none fixed inset-0 dot-field opacity-40" />
    <nav className="relative mx-auto flex w-full max-w-6xl items-center justify-between px-6 py-6 md:px-10"><Link href="/" className="flex items-center gap-2 font-mono text-sm font-bold tracking-[-0.08em]"><span className="grid h-8 w-8 place-items-center rounded-full border border-[#9eff6b] text-[#9eff6b]">B</span><span className="tracking-[-0.06em]">BERLABS</span></Link><div className="flex items-center gap-5 font-mono text-xs uppercase tracking-[0.12em] text-[#b8c7bd]"><Link className="hidden transition hover:text-[#9eff6b] sm:block" href="/issues">Issues</Link><a className="rounded-full border border-[#9eff6b] px-4 py-2 text-[#9eff6b] transition hover:bg-[#9eff6b] hover:text-[#071716]" href="#subscribe">Subscribe</a></div></nav>
    <section className="relative mx-auto grid max-w-6xl gap-12 px-6 pb-20 pt-16 md:grid-cols-[1.2fr_.8fr] md:px-10 md:pb-28 md:pt-24"><div className="max-w-3xl"><p className="mb-6 font-mono text-xs uppercase tracking-[0.2em] text-[#9eff6b]">Dispatches for the curious</p><h1 className="text-balance font-serif text-5xl leading-[.93] tracking-[-0.06em] sm:text-6xl md:text-8xl">Stay awake to what&apos;s next.</h1><p className="mt-8 max-w-xl text-lg leading-8 text-[#b8c7bd]">BerLabs is a calm, useful newsletter about AI, the internet, and the ideas changing how we make things.</p><a className="mt-9 inline-flex items-center gap-3 rounded-full bg-[#9eff6b] px-6 py-3 font-mono text-sm font-semibold text-[#071716] transition hover:scale-[1.02]" href="#subscribe">Get the next issue <span aria-hidden="true">↗</span></a></div><aside className="self-end border-l border-[#b8c7bd]/25 pl-6 md:pb-2 md:pl-10"><p className="font-mono text-xs uppercase tracking-[0.16em] text-[#b8c7bd]">Written by</p><p className="mt-3 font-serif text-3xl tracking-[-0.04em]">Kody</p><p className="mt-5 max-w-xs text-sm leading-6 text-[#b8c7bd]">No daily noise. Just a thoughtful signal when there is something worth sharing.</p></aside></section>
    <section className="relative border-y border-[#b8c7bd]/20 bg-[#0b2220]/80"><div className="mx-auto grid max-w-6xl gap-8 px-6 py-10 md:grid-cols-[.65fr_1.35fr] md:px-10 md:py-14"><p className="font-mono text-xs uppercase tracking-[0.18em] text-[#9eff6b]">Latest dispatch</p><article><p className="font-mono text-xs uppercase tracking-[0.13em] text-[#b8c7bd]">{currentIssue.date}</p><h2 className="mt-3 font-serif text-4xl tracking-[-0.05em] md:text-5xl">{currentIssue.title}</h2><p className="mt-4 max-w-xl text-base leading-7 text-[#b8c7bd]">{currentIssue.description}</p><Link className="mt-6 inline-flex border-b border-[#9eff6b] pb-1 font-mono text-sm text-[#9eff6b] transition hover:text-white" href="/issues">Read the archive</Link></article></div></section>
    <section id="subscribe" className="relative mx-auto grid max-w-6xl gap-8 px-6 py-20 md:grid-cols-[1fr_1fr] md:px-10 md:py-28"><div><p className="font-mono text-xs uppercase tracking-[0.18em] text-[#9eff6b]">The next note is yours</p><h2 className="mt-5 max-w-lg font-serif text-4xl leading-none tracking-[-0.05em] md:text-5xl">A better inbox starts with fewer, better emails.</h2></div><div className="self-end rounded-[1.5rem] border border-[#9eff6b]/40 bg-[#102d29] p-7"><p className="max-w-sm text-base leading-7 text-[#d7e2d6]">Sign up through the BerLabs member portal. You can leave whenever you want.</p><a className="mt-6 inline-flex w-full items-center justify-between rounded-xl bg-[#9eff6b] px-5 py-4 font-mono text-sm font-semibold text-[#071716] transition hover:bg-[#b5ff90]" href="https://archive.berlabs.dev/#/portal/signup">Subscribe to BerLabs <span aria-hidden="true">↗</span></a></div></section>
    <footer className="relative mx-auto flex max-w-6xl flex-col gap-3 border-t border-[#b8c7bd]/20 px-6 py-7 font-mono text-xs uppercase tracking-[0.13em] text-[#799187] sm:flex-row sm:items-center sm:justify-between md:px-10"><span>BerLabs · written by Kody</span><Link className="transition hover:text-[#9eff6b]" href="/issues">Archive</Link></footer>
  </main>;
}
